Repository open-mmlab/mmpose, pull requests merged in 2021-06, with the labels that each got.

#667 Rename heads detectors
  docs/api.rst
  docs/tutorials/0_config.md
  docs/tutorials/1_finetune.md
  mmpose/deprecated.py
  mmpose/models/__init__.py
  mmpose/models/detectors/__init__.py
  mmpose/models/detectors/associative_embedding.py
  mmpose/models/detectors/mesh.py
  mmpose/models/heads/__init__.py
  mmpose/models/heads/ae_higher_resolution_head.py
  mmpose/models/heads/ae_simple_head.py
  mmpose/models/heads/deeppose_regression_head.py
  mmpose/models/heads/hmr_head.py
  mmpose/models/heads/interhand_3d_head.py
  mmpose/models/heads/temporal_regression_head.py
  mmpose/models/heads/topdown_heatmap_base_head.py
  mmpose/models/heads/topdown_heatmap_multi_stage_head.py
  mmpose/models/heads/topdown_heatmap_simple_head.py
  mmpose/models/keypoint_heads/__init__.py
  mmpose/models/losses/mesh_loss.py
  mmpose/models/mesh_heads/__init__.py
  mmpose/models/misc/__init__.py
  mmpose/models/misc/discriminator.py
  mmpose/models/utils/geometry.py
  tests/test_loss/test_mesh_losses.py
  tests/test_model/test_bottom_up_forward.py
  tests/test_model/test_bottom_up_head.py
  tests/test_model/test_mesh_head.py
  tests/test_model/test_top_down_forward.py
  tests/test_model/test_top_down_head.py
Labels: breaking change

#713 Fix h36m preproc
  tools/dataset/h36m_to_coco.py
  tools/dataset/preprocess_h36m.py
Labels: need tests

#742 ViPNAS ResNet
  configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/coco/vipnas_coco.md
  configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/coco/vipnas_res50_coco_256x192.py
  docs/papers/backbones/vipnas.md
  mmpose/core/evaluation/top_down_eval.py
  mmpose/core/post_processing/post_transforms.py
  mmpose/datasets/pipelines/top_down_transform.py
  mmpose/models/backbones/__init__.py
  mmpose/models/backbones/vipnas_resnet.py
  mmpose/models/heads/__init__.py
  mmpose/models/heads/vipnas_heatmap_simple_head.py
  tests/test_backbones/test_vipnas.py
  tests/test_model/test_top_down_forward.py
  tests/test_model/test_top_down_head.py
Labels: need doc
